import type { Metadata } from "next";
import "./globals.css";

import Layout from "@src/layout";
import { AppProviders } from "@src/components";
import { auth } from "@src/libs";

export const metadata: Metadata = {
  title: "Blog-App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/icon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <head />
      <body>
        <AppProviders>
          <Layout user={session?.user}>{children}</Layout>
        </AppProviders>
      </body>
    </html>
  );
}
